name: Cloud Run Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          version: 'latest'
          project_id: house-scraper-ag
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Docker image
        run: |
          gcloud builds submit --tag gcr.io/$PROJECT_ID/real-estate-scraper

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy scraper-cr --image gcr.io/$PROJECT_ID/real-estate-scraper --platform managed
